/* ============================================
   exams_data.js — 9套试卷题库（由Word导入转换）
   补充 Defaults.exams
   ============================================ */

Defaults.exams = {

    "exam-xwgf": {
        title: "团播行为规范考试",
        questions: [
            { id: 1, type: "single", question: "下述女团服装不符合哪项60分要求？（单选）",
              images: ["images/exam-xwgf/image1.png"],
              options: ["A. 全员不能穿短裙","B. 全员不能穿紧身性感类服装","C. 不能穿黑丝","D. 全员肩颈裸露"],
              answer: [1],
              explanation: "全员不能穿紧身性感类服装属于60分规范要求。" },
            { id: 2, type: "single", question: "下述女团服装不符合哪项60分要求？（单选）",
              images: ["images/exam-xwgf/image2.png"],
              options: ["A. 全员不能穿短裙","B. 全员不能穿紧身性感类服装","C. JK制服/校服类幼态装扮","D. 全员肩颈裸露"],
              answer: [2],
              explanation: "JK制服/校服类幼态装扮属于违规着装类型。" },
            { id: 3, type: "multiple", question: "下述团播画面不符合哪项60分要求？（多选）",
              images: ["images/exam-xwgf/image3.png"],
              options: ["A. 大面积纹身","B. 全员不能穿短裙","C. 全员肩颈裸露","D. 1/2以上人员穿透明凉鞋或拖鞋","E. 互动·惩罚游戏"],
              answer: [0,3,4],
              explanation: "大面积纹身、1/2以上人员穿透明凉鞋或拖鞋、互动·惩罚游戏均不符合60分要求。" },
            { id: 4, type: "single", question: "下述团播画面不符合哪项60分要求？（单选）",
              images: ["images/exam-xwgf/image4.png"],
              options: ["A. 全员紧身性感类服装","B. 贴纸不当表述（贴纸没有对应舞蹈名称）","C. 1/2以上人员穿透明凉鞋或拖鞋","D. 全员肩颈裸露"],
              answer: [1],
              explanation: "贴纸不当表述（贴纸没有对应舞蹈名称）是常见违规项。" },
            { id: 5, type: "multiple", question: "下述团播画面不符合哪项60分要求？（多选）",
              images: ["images/exam-xwgf/image5.png","images/exam-xwgf/image6.png"],
              options: ["A. 大面积纹身","B. 不符合的特殊玩法-营造噱头（假装亲吻）","C. 不符合的特殊玩法-营造噱头（抚摸敏感部位）","D. 上装腰腹裸露超过一巴掌（透视装/渔网装）"],
              answer: [0,1,2,3],
              explanation: "以上四项均不符合60分要求。" },
            { id: 6, type: "single", question: "团播账号「60分」打分在哪里看？（单选）",
              images: [],
              options: ["A. 公会后台-主播列表-团播-评级明细","B. 公会后台-公会信息-健康分","C. 抖音app-我的-主播健康分"],
              answer: [0],
              explanation: "正确路径：公会后台 → 主播列表 → 团播 → 评级明细。" },
            { id: 7, type: "single", question: "团播账号「60分」打分周期是？（单选）",
              images: [],
              options: ["A. 每个自然月","B. 上月25号-本月25号"],
              answer: [1],
              explanation: "打分周期为上月25号至本月25号，非自然月。" },
            { id: 8, type: "single", question: "如何能提高团播账号达标率？（单选）",
              images: [],
              options: ["A. 平时不看达标状态，等到25号再看达不达标","B. 每天在公会后台查看达标状态与评级明细，发现0分场次立刻整改","C. 平时只看达标状态，不看评级明细，有0分问题也不知道"],
              answer: [1],
              explanation: "每天查看并立即整改是提高达标率的正确做法。" },
            { id: 9, type: "multiple", question: "团播账号显示「不达标」（低于60分）对公会有什么影响？（多选）",
              images: [],
              options: ["A. 不达标团对应月份的所有公会收益全部扣除","B. 公会团播60分达标率≤65%且底线类违规场次占比过高，将命中公会准出处罚（首次警告，连续2次落罚公会）","C. 对公会没有影响"],
              answer: [0,1],
              explanation: "不达标会导致收益扣除和公会处罚，对公会影响严重。" },
            { id: 10, type: "multiple", question: "以下属于60分高频违规案例场景的是？（多选）",
              images: [],
              options: ["A. 禁止教室/校园、法庭、医院、办公室等特殊场景娱乐化呈现","B. 禁止团播场景下的营收竞争玩法过程中通过任何形式呈现遮挡模糊人脸或身体","C. 禁止通过在包间围/转餐桌跳舞互动","D. 禁止团播场景下出现模仿选秀场景（制服感）、贴名牌"],
              answer: [0,1,2,3],
              explanation: "以上四项均为60分高频违规案例场景。" },
            { id: 11, type: "multiple", question: "以下画面贴纸不符合60分要求的是？（多选）",
              images: ["images/exam-xwgf/image7.png","images/exam-xwgf/image8.png","images/exam-xwgf/image9.png"],
              options: ["A. 选项1","B. 选项2","C. 选项3"],
              answer: [0,1,2],
              explanation: "（本题为图片题，需对照实际图片判断）" },
            { id: 12, type: "single", question: "下述团播画面不符合哪项60分要求？（单选）",
              images: ["images/exam-xwgf/image10.png"],
              options: ["A. 露沟","B. 全员性感紧身服饰","C. 美颜拉腿过度"],
              answer: [1],
              explanation: "全员性感紧身服饰是明确违规项。" },
            { id: 13, type: "multiple", question: "下述团播画面不符合哪项60分要求？（多选）",
              images: ["images/exam-xwgf/image11.png"],
              options: ["A. 露沟","B. 违规道具（兔耳朵等）","C. 超短裙裤露出打底裤或者下臀线","D. 大面积裸露（透视装、渔网类等于裸露）"],
              answer: [0,1,2,3],
              explanation: "以上四项均为违规着装和道具。" },
            { id: 14, type: "single", question: "对下述团播画面的描述正确的是？（单选）",
              images: ["images/exam-xwgf/image12.png"],
              options: ["A. 肩颈大面积裸露","B. 不良竞争仇视推搡"],
              answer: [1],
              explanation: "（本题为图片题）不良竞争仇视推搡属于违规行为。" },
            { id: 15, type: "multiple", question: "下述图片不符合60分要求的是？（多选）",
              images: ["images/exam-xwgf/image13.png","images/exam-xwgf/image14.png","images/exam-xwgf/image15.png","images/exam-xwgf/image16.png"],
              options: ["A. 选项1","B. 选项2","C. 选项3","D. 选项4"],
              answer: [0,1,2,3],
              explanation: "（本题为图片题，需对照实际图片判断）" }
        ]
    },

    "exam-smts": {
        title: "团播审美能力提升",
        questions: [
            { id: 1, type: "multiple", question: "以下内容哪些属于审美提升范畴？（多选）",
              images: [],
              options: ["A. 直播场地&背景","B. 主播的服化道","C. 灯光","D. 上镜效果"],
              answer: [0,1,2,3],
              explanation: "以上四项全部属于审美提升范畴。" },
            { id: 2, type: "multiple", question: "以下关于审美提升说法正确的是？（多选）",
              images: [],
              options: ["A. 在70分规范合格线的基础上做审美优化","B. 定期查看团播内容管理规范文档，了解熟读最新违规点","C. 流量才是王道，创新一些猎奇点做吸引，符合70分规范有太多局限性"],
              answer: [0,1],
              explanation: "应在规范合格线基础上做优化，并定期学习最新规范。不能用猎奇内容替代规范。" },
            { id: 3, type: "single", question: "以下关于女团审美提升做法正确的是？（单选）",
              images: [],
              options: ["A. 女团画风只由男运营团队负责管理","B. 女团画风增加女运营审美视角，对应粉丝市场"],
              answer: [1],
              explanation: "增加女运营审美视角能更好地对应粉丝市场。" },
            { id: 4, type: "multiple", question: "如何更好的提升审美？（多选）",
              images: [],
              options: ["A. 多刷直播平台、种草平台等，了解当下主流审美","B. 内部定期组织审美会，提升美感","C. 针对不同团的定位找到适合的对标运营团体做审美校验","D. 关注最终上镜效果，不追求过分夸大美颜、身材比例","E. 总结整理公司内部审美素材库，例如妆容、发型、服装等"],
              answer: [0,1,2,3,4],
              explanation: "以上五项都是提升审美的有效方法。" },
            { id: 5, type: "multiple", question: "请选择以下正向主流审美画风的示例？（多选）",
              images: ["images/exam-smts/image1.png","images/exam-smts/image2.png","images/exam-smts/image3.png","images/exam-smts/image4.png"],
              options: ["A. 选项1","B. 选项2","C. 选项3","D. 选项4"],
              answer: [1,2,3],
              explanation: "（本题为图片题，选项2/3/4为正向示例）" },
            { id: 6, type: "multiple", question: "请选择正向的服化道示例？（多选）",
              images: ["images/exam-smts/image5.png","images/exam-smts/image6.png","images/exam-smts/image7.png","images/exam-smts/image8.png","images/exam-smts/image9.png"],
              options: ["A. 妆容","B. 眼妆","C. 发型","D. 造型","E. 服装"],
              answer: [0,3,4],
              explanation: "妆容、造型、服装是服化道的三个核心要素。" },
            { id: 7, type: "single", question: "如何正确筛选团员？（单选）",
              images: [],
              options: ["A. 好看就行，不考虑其他因素","B. 考察主播整体形象，包括脸型、五官、身材比例对应上镜效果"],
              answer: [1],
              explanation: "筛选团员需综合考察整体形象和上镜效果。" },
            { id: 8, type: "multiple", question: "从脸型角度出发，以下哪些是符合团播成员上镜标准的？（多选）",
              images: [],
              options: ["A. 女生：鹅蛋脸＞菱形脸＞圆形脸＞长型脸＞国字脸","B. 女生：长型脸＞鹅蛋脸＞圆形脸＞菱形脸＞国字脸","C. 男生：鹅蛋脸＞国字脸＞菱形脸＞长形脸＞圆形脸","D. 男生：国字脸＞菱形脸＞鹅蛋脸＞长形脸＞圆形脸"],
              answer: [0,2],
              explanation: "女生优先鹅蛋脸，男生优先鹅蛋脸。这是团播上镜的优选脸型排序。" },
            { id: 9, type: "multiple", question: "从五官角度出发，以下哪些是符合团播成员上镜标准的？（多选）",
              images: [],
              options: ["A. 女生重点关注五官分散度（三庭五眼）","B. 男生重点关注五官立体度（四高三低）","C. 女生在化妆帮助下，五官分布的小劣势会有所改善","D. 男生化妆基本只优化皮肤和发型，较依赖原生长相的立体度"],
              answer: [0,1,2,3],
              explanation: "以上四项均正确。女生注重三庭五眼+化妆改善，男生注重四高三低+原生长相。" },
        ]
    },

    "exam-llwf": {
        title: "团播流量玩法能力测试",
        questions: [
            { id: 1, type: "multiple", question: "以下哪项是影响流量的互动指标？（多选）",
              images: [],
              options: ["A. 付费率","B. 弹幕评论","C. 关注","D. 观众停留时长","E. 点赞"],
              answer: [0,1,2,3,4],
              explanation: "以上五项均为影响流量的核心互动指标。" },
            { id: 2, type: "multiple", question: "以下哪项是影响流量的账号指标？（多选）",
              images: [],
              options: ["A. 近期有多次违规导致账号封禁","B. 账号曾借出给他人从事违法违规行为","C. 直播内容、直播间标题、直播间简介明显有色情低俗导向"],
              answer: [0,1,2],
              explanation: "以上三项均会影响账号流量。" },
            { id: 3, type: "multiple", question: "以下哪项是流量重要来源渠道？（多选）",
              images: [],
              options: ["A. 自然推荐流量","B. 关注天窗","C. 分享推荐","D. 同城推荐"],
              answer: [0,1,2,3],
              explanation: "以上四项均为重要流量来源渠道。" },
            { id: 4, type: "single", question: "以下关于团播起流阶段说法错误的是？（单选）",
              images: [],
              options: ["A. 新团起流阶段，应该打开所有流量入口，尽可能获取流量","B. 新团起流阶段，应该关闭搜索、同城，也不分享直播间到粉丝群"],
              answer: [1],
              explanation: "关闭搜索和同城是错误的做法，应该合理利用所有流量入口。" },
            { id: 5, type: "multiple", question: "团播账号提营收提流量，可以在直播伴侣中使用的工具有哪些？（多选）",
              images: [],
              options: ["A. 团播管理","B. 抖音电商","C. 互动工具","D. 游戏推广"],
              answer: [0,2],
              explanation: "团播管理和互动工具是提营收提流量的核心工具。" },
            { id: 6, type: "multiple", question: "整体可以提升流量做优化的手段有？（多选）",
              images: [],
              options: ["A. 内容创新","B. 主持人话术优化","C. 借助工具进行定向的数据优化，提升流量"],
              answer: [0,1,2],
              explanation: "内容创新、话术优化和数据优化是提升流量的三大手段。" },
            { id: 7, type: "multiple", question: "从流量工具角度出发，有哪些提流量的玩法方式？（多选）",
              images: ["images/exam-gjsy/image5.png","images/exam-gjsy/image6.png","images/exam-gjsy/image3.png","images/exam-gjsy/image4.png"],
              options: ["设计飞行嘉宾玩法，丰富直播内容","提升直播内容，冲击团播榜单/团员榜单","开启团员共创，获得更多流量分发","团播账号厂牌设置"],
              answer: [0,1,2,3],
              explanation: "以上四项都是有效的提流量玩法。" },
            { id: 8, type: "single", question: "从合规角度，做流量玩法的基础前提是？（单选）",
              images: [],
              options: ["A. 整体内容符合70分规范要求，做优质内容输出","B. 为了流量，增加一些低俗噱头内容，先把人吸引过来再说"],
              answer: [0],
              explanation: "合规是基础，必须在符合70分规范的前提下做流量。" },
            { id: 9, type: "single", question: "如何快速提升团播流量玩法效率？（单选）",
              images: [],
              options: ["A. 公会内部集思广益，摸索新玩法模式","B. 善于利用官方玩法提效，合理利用女神快跑、水果切切切、大鱼吃小鱼等互动特效玩法"],
              answer: [1],
              explanation: "利用官方提供的互动特效玩法能快速提升效率。" }
        ]
    },

    "exam-kblc": {
        title: "团播开播流程能力测试",
        questions: [
            { id: 1, type: "multiple", question: "在内容输出角度，开播流程环节前需要做的前置动作是？（多选）",
              images: [],
              options: ["A. 筛选成员：脸型、五官、身材比例","B. 要做什么类型的团：男粉市场、女粉市场","C. 找到优质对标团，做内容拆解","D. 按照积累的丰富行业直播经验直接开播"],
              answer: [0,1,2],
              explanation: "筛选成员、定位市场、对标拆解是开播前的必要前置动作。" },
            { id: 2, type: "multiple", question: "开播前团播成员能力培养需要关注的是？（多选）",
              images: [],
              options: ["A. 舞蹈能力","B. 表现力","C. 互动能力"],
              answer: [0,1,2],
              explanation: "舞蹈能力、表现力和互动能力是团播成员的三大核心能力。" },
            { id: 3, type: "multiple", question: "在操作流程上，开播前的检查动作有哪些？（多选）",
              images: [],
              options: ["A. 硬件操作：灯光、背景、摄影摄像设备","B. 软件操作：直播伴侣、美颜软件、音频软件、特效视频剪辑软件","C. 检查主播状态：主播服装、站位等"],
              answer: [0,1,2],
              explanation: "硬件、软件、主播状态三方面都需要检查到位。" },
            { id: 4, type: "multiple", question: "以下关于开播说法正确的是？（多选）",
              images: [],
              options: ["A. 明确直播数据目标，让团队里的每一个人都参与到数据提升的目标中来","B. 选定好开播时间就不要经常变动，通过一周的观察再决定是否换时间","C. 新号开播要抢占晚间黄金档，不考虑其他时间段","D. 直播封面和标题通过不断实验慢慢调整，从曝光率到进入率做提升"],
              answer: [0,1,3],
              explanation: "新号不应盲目抢占黄金档，其他三项正确。" },
            { id: 5, type: "single", question: "整个开播直播阶段，容易被忽视的关键动作是？（单选）",
              images: [],
              options: ["A. 直播内容优化","B. 下播复盘"],
              answer: [1],
              explanation: "下播复盘是最容易被忽视但非常关键的动作。" },
            { id: 6, type: "single", question: "以下开播标题，不符合直播行为规范的是（单选）",
              images: [],
              options: ["A. 刷点吧 就当喂猪了","B. 输入VR进入第三视角OOC致歉","C. 前30分钟不换人，感谢理解"],
              answer: [0],
              explanation: "带有侮辱性质的开播标题不符合直播行为规范。" },
            { id: 7, type: "multiple", question: "开播过程中，直播画面突然被屏蔽或者封禁，以下处理流程正确的是（多选）",
              images: [],
              options: ["A. 不管不顾，不做任何调整","B. 主持及时制止可能涉及违规画面出镜，及时记录情况便于下播复盘改进","C. 如遇到封禁，及时申诉并根据违规提示和对应画面进行复盘","D. 如遇到封禁，不申诉，不做任何复盘，认定有人恶意举报"],
              answer: [1,2],
              explanation: "及时制止违规画面、记录复盘，并进行申诉是正确流程。" },
            { id: 8, type: "multiple", question: "复盘需要关注以下哪些方面？（多选）",
              images: [],
              options: ["A. 下播后大家各自发表想法，沟通一下即可","B. 结合后台数据诊断，定位问题点，做后续内容优化","C. 重点分析峰值、趋势等变化带来的信号释放，制定对应调整措施"],
              answer: [1,2],
              explanation: "复盘需要结合数据进行诊断和定位，而非泛泛沟通。" },
            { id: 9, type: "multiple", question: "以下关于团播-团员共创工具，说法正确的是（多选）",
              images: [],
              options: ["A. 开播不能使用团员共创功能，会影响主账号推流","B. 若团员账号未实名或未成年、近45天有严重违规记录、账号历史存在违规情况不支持开启","C. 首次勾选会有用户协议弹窗，需同意功能协议后才能开启","D. 团员授权共创后，如果播中未检测到成员在直播间内，会提示"],
              answer: [1,2,3],
              explanation: "团员共创不会影响主账号推流，其他三项正确。" }
        ]
    },

    "exam-gjsy": {
        title: "团播工具使用基础",
        questions: [
            { id: 1, type: "multiple", question: "团播账号提营收提流量，可以在直播伴侣中使用的工具有哪些？（多选）",
              images: [],
              options: ["A. 团播管理","B. 抖音电商","C. 互动工具","D. 游戏推广"],
              answer: [0,2],
              explanation: "团播管理和互动工具是直播伴侣中提营收提流量的核心工具。" },
            { id: 2, type: "single", question: "以下哪种方式可以自助获得「团播管理」功能权限？（单选）",
              images: ["images/exam-gjsy/image2.png","images/exam-gjsy/image3.png"],
              options: ["A. 邀约入会时标记为「团播主播」","B. 主播列表选择主播标记为团播"],
              answer: [1],
              explanation: "在主播列表选择主播标记为团播即可获得团播管理功能。" },
            { id: 3, type: "multiple", question: "以下属于「团播管理」工具功能的是？（多选）",
              images: [],
              options: ["A. 团播管理玩法（投票/榜单/限时竞争）","B. 流量工具","C. 公会赛工具","D. 互动工具"],
              answer: [0,1,2,3],
              explanation: "以上四项均属于团播管理工具的功能。" },
            { id: 4, type: "multiple", question: "以下哪些是「团播管理」界面支持的功能？（多选）",
              images: [],
              options: ["A. 团员管理（开播可勾选团员共创）","B. 团员计票（可支持自动计票/计分）","C. 礼物点舞（横屏/竖屏展示皆可，礼物必须对应舞蹈名称）","D. 限时竞争（双人/多人PK血条）","E. 单人/双人指定礼物闯关（刺客玩法，支持指定礼物延长时间）","F. 团员榜单（支持淘汰/复活）"],
              answer: [0,1,2,3,4,5],
              explanation: "以上六项均为团播管理界面支持的功能。" },
            { id: 5, type: "multiple", question: "团播账号和团员账号如何才能上团播榜单？（多选）",
              images: [],
              options: ["A. 符合团播60分规范","B. 无严重违规封禁（近45天封禁天数小于30天）","C. 团播账号开启共创分发","D. 团员账号进行共创授权"],
              answer: [0,1,2,3],
              explanation: "以上四项均为上团播榜单的前提条件。" },
            { id: 6, type: "multiple", question: "以下关于「团员共创」能力，说法正确的是？（多选）",
              images: [],
              options: ["A. 新号需要稳定播几天团播内容，才能激活团员共创入口，刚开播是没有共创的","B. 开启共创，可以为团播账号带来更多流量","C. 「60分」以下团播账号没有共创权限，也不支持特殊申请","D. 团员共创的开启入口：直播伴侣-团播管理-团员管理-流量共享","E. 邀请团员加入共创，不需要团员在账号app内点击确认"],
              answer: [0,1,2,3],
              explanation: "邀请团员加入共创需要团员在app内点击确认，其他四项正确。" },
            { id: 7, type: "multiple", question: "以下工具对于帮助提升「用户付费1毛钱」的是？（多选）",
              images: ["images/exam-gjsy/image7.png","images/exam-gjsy/image8.png","images/exam-gjsy/image9.png","images/exam-gjsy/image10.png"],
              options: ["A. 礼物投票工具","B. 加减挑战工具","C. 计数挑战工具","D. 弹幕投票"],
              answer: [0,1,2],
              explanation: "礼物投票、加减挑战、计数挑战均有助于提升用户付费意愿。" },
            { id: 8, type: "multiple", question: "以下哪些是「互动工具」内可以支持的功能？（多选）",
              images: [],
              options: ["A. 水果切切切、大鱼吃小鱼、pose挑战、躲避小鸟","B. 弹幕投票工具、礼物投票工具、翻牌才艺秀、加减挑战","C. 打分工具、提问板、集赞集礼物、倒计时","D. 冰封挑战、玫瑰缠绕"],
              answer: [0,1,2,3],
              explanation: "以上四项均为互动工具内支持的功能。" },
            { id: 9, type: "multiple", question: "以下关于团播工具看法正确的是？（多选）",
              images: [],
              options: ["A. 选择合适的工具丰富团播内容，对流量/营收非常重要","B. 根据团播内容去尝试不同的工具，来提升互动指标","C. 保持和提升现有直播内容，不做团播工具尝试","D. 特殊节点上新的团播工具第一时间使用，抢占第一波新鲜感"],
              answer: [0,1,3],
              explanation: "应积极尝试团播工具来提升内容质量，而非固守不变。" },
            { id: 10, type: "truefalse", question: "关播时在场上的成员需要在20分钟内完成人脸录入并提交，如果超时可以补交，补录本场直播的关播人脸信息。",
              images: [],
              options: ["正确","错误"],
              answer: [1],
              explanation: "超过20分钟不可补录。拉新阶段每个周期内超过≥3次超时将被判定为拉新作弊。" },
            { id: 11, type: "single", question: "关于开播前和下播后录入人脸的时间限时为多久？（单选）",
              images: [],
              options: ["A. 10分钟","B. 15分钟","C. 20分钟","D. 25分钟"],
              answer: [2],
              explanation: "开播前和下播后人脸录入限时为20分钟。" },
            { id: 12, type: "multiple", question: "开播录入人脸的方式有哪几种？（多选）",
              images: [],
              options: ["A. 直播伴侣录入","B. 第三方软件录入","C. 手机端扫码录入","D. 截图拍照录入"],
              answer: [0,2],
              explanation: "只有直播伴侣录入和手机端扫码录入两种方式。" },
            { id: 13, type: "truefalse", question: "如果主播选择用手机录入上下播人脸需主播在抖音同意授权信息即可。",
              images: [],
              options: ["正确","错误"],
              answer: [1],
              explanation: "除在抖音授权外，还需在手机设置中给抖音APP授权相机拍照权限和精准定位功能，少一个都会影响统计。" },
            { id: 14, type: "truefalse", question: "如果使用伴侣端录入人脸需要先发送[申请授权]信息到主播的抖音站内信息点授权才可以使用。",
              images: [],
              options: ["正确","错误"],
              answer: [0],
              explanation: "使用电脑直播伴侣录入人脸，需要先发送申请授权信息给主播，主播在抖音确认授权后才能正常使用。" }
        ]
    },

    "exam-zhjc": {
        title: "团播综合基础能力",
        questions: [
            { id: 1, type: "multiple", question: "以下画面贴纸不符合60分要求的是？（多选）",
              images: ["images/exam-zhjc/image1.png","images/exam-zhjc/image2.png","images/exam-zhjc/image3.png"],
              options: ["A. 贴纸未对应舞蹈名称","B. 贴纸遮挡人物主体","C. 礼物点人"],
              answer: [0,1,2],
              explanation: "贴纸未对应舞蹈名称、遮挡主体、礼物点人均不符合60分要求。" },
            { id: 2, type: "multiple", question: "以下服装穿法不符合60分要求的是？（多选）",
              images: ["images/exam-zhjc/image4.png","images/exam-zhjc/image5.png","images/exam-zhjc/image7.png","images/exam-zhjc/image8.png"],
              options: ["A. 漏沟","B. 漏下臀线","C. 全员紧身类服装","D. 肩颈裸露"],
              answer: [0,1,2],
              explanation: "漏沟、漏下臀线、全员紧身类服装均不符合60分要求。" },
            { id: 3, type: "single", question: "下述画面不符合哪项60分要求？（单选）",
              images: ["images/exam-zhjc/image8.png"],
              options: ["A. 不能全员穿短裤","B. 不能全员穿紧身性感类服装","C. 不能呈现背身/转身玩法","D. 出现肩颈大面积裸露"],
              answer: [2],
              explanation: "呈现背身/转身玩法是不符合60分要求的违规行为。" },
            { id: 4, type: "multiple", question: "下述画面哪些不符合60分要求？（多选）",
              images: ["images/exam-zhjc/image9.png","images/exam-zhjc/image10.png","images/exam-zhjc/image11.png"],
              options: ["A. 昏暗场景下刻意凸显身材营造低俗氛围","B. 接下班/接放学","C. 长/短腿特效博眼球"],
              answer: [0,1,2],
              explanation: "以上三项均不符合60分要求。" },
            { id: 5, type: "single", question: "【高频场景判断题】关于下述画面说法正确的是？（单选）",
              images: ["images/exam-zhjc/image12.png"],
              options: ["A. 正确，多角度场景创新","B. 错误，仰拍场景营造低俗感知"],
              answer: [1],
              explanation: "仰拍场景营造低俗感知，属于违规。" },
            { id: 6, type: "single", question: "团播账号「60分」打分明细哪里看？（单选）",
              images: [],
              options: ["A. 公会后台-公会信息-健康分","B. 抖音app-我的-主播健康分","C. 公会后台-主播列表-团播-是否达标","D. 公会后台-主播列表-团播-评级明细"],
              answer: [3],
              explanation: "在公会后台-主播列表-团播-评级明细中查看。" },
            { id: 7, type: "single", question: "团播账号「60分」打分周期是？（单选）",
              images: [],
              options: ["A. 每个自然月","B. 上月25号-本月25号"],
              answer: [1],
              explanation: "打分周期为上月25号至本月25号。" },
            { id: 8, type: "multiple", question: "团播账号显示「不达标」（低于60分）对公会有什么影响？（多选）",
              images: [],
              options: ["A. 不达标团对应月份的所有公会收益全部扣除","B. 公会团播60分达标率≤65%且底线类违规场次占比过高，将命中公会准出处罚（首次警告，连续2次落罚公会）","C. 对公会没有影响"],
              answer: [0,1],
              explanation: "不达标将导致收益扣除和公会处罚。" },
            { id: 9, type: "multiple", question: "团播账号有拉新任务的前提是？（多选）",
              images: [],
              options: ["A. 老团把账号注销，重新注册账号，也能有拉新","B. 账号成员都是首次在抖音露脸","C. 账号邀约入会时选择「新主播」+「团播主播」身份"],
              answer: [1,2],
              explanation: "首次露脸+正确入会标签是拉新前提。" },
            { id: 10, type: "single", question: "团播账号参与的是以下哪大类公会任务？（单选）",
              images: [],
              options: ["A. 语音聊天室任务","B. 宫格聊天室任务","C. 视频个播任务/新公会任务","D. 虚拟任务","E. 电台任务"],
              answer: [2],
              explanation: "团播账号参与视频个播任务/新公会任务。" },
        ]
    },

    "exam-hfyt": {
        title: "团播画风调优基础",
        questions: [
            { id: 1, type: "single", question: "做好团播画风的前提是？（单选）",
              images: [],
              options: ["A. 先通读「60分」服化道要求，服化道是常见违规项，前置做好学习能有效减少收益损失","B. 什么衣服都能穿，直接买就完事"],
              answer: [0],
              explanation: "先学习60分规范要求是做好画风的前提。" },
            { id: 2, type: "multiple", question: "做好画风调优的有效动作是？（多选）",
              images: [],
              options: ["A. 风格：明确团风格&团员人设，对标相关高热账号拆解学习","B. 场地：直播场地搭建&背景布置","C. 服化道：根据风格，给每位成员明确妆容、发型、穿搭","D. 灯光：调试场地灯光，进行布光搭配","E. 上镜：调整上镜效果，包括上镜比例、美颜参数、开播清晰度等"],
              answer: [0,1,2,3,4],
              explanation: "以上五个维度（风格、场地、服化道、灯光、上镜）是画风调优的核心动作。" },
            { id: 3, type: "multiple", question: "下述「室内直播间」场景搭建描述正确的是？（多选）",
              images: [],
              options: ["A. 避免场景过于简单只加顶灯，营造KTV氛围感","B. 避免使用星空幕布","C. 避免舞台背景过于复杂，图案小而乱","D. 根据每天直播内容和妆造不同，变化LED屏的素材，更好适配画风"],
              answer: [0,1,2,3],
              explanation: "以上四项均为室内直播间场景搭建的正确做法。" },
            { id: 4, type: "multiple", question: "下述哪些行为会命中「涉及性暗示的擦边内容」违规？（多选）",
              images: [],
              options: ["A. 聚焦胸部，通过影子的方式凸显身材轮廓","B. 抚摸揉捏抖动胸部，胸部塞取东西，下体夹东西"],
              answer: [0,1],
              explanation: "以上行为均涉及性暗示擦边内容。" },
            { id: 5, type: "single", question: "团播直播间设备选择应该？（单选）",
              images: [],
              options: ["A. 一上来就整高配，成本拉满","B. 先看利润，再倒推成本，优先跑通流程后再做高端设备投入"],
              answer: [1],
              explanation: "先验证盈利模式，再合理投入设备升级。" },
            { id: 6, type: "single", question: "以下主播妆容，与图片对应的风格顺序为？（单选）",
              images: ["images/exam-hfyt/image1.png"],
              options: ["A. 国风→复古→甜美→酷飒","B. 复古→国风→酷飒→甜美","C. 甜美→国风→酷飒→复古","D. 甜美→国风→复古→酷飒"],
              answer: [3],
              explanation: "正确顺序：甜美→国风→复古→酷飒。需对照图片判断。" },
            { id: 7, type: "multiple", question: "以下主播发型存在问题是？（多选）",
              images: ["images/exam-hfyt/image2.png"],
              options: ["A. 头发显油/显秃","B. 头发过于贴头皮","C. 发型随意，没有造型","D. 没有问题"],
              answer: [0,1,2],
              explanation: "主播发型应保持清爽蓬松有造型。ABC均为常见问题。" },
            { id: 8, type: "multiple", question: "以下布光思路正确的是？（多选）",
              images: [],
              options: ["A. 基础必备灯光配置为：面光+腿光+轮廓光","B. 根据不同直播间场地要做细节上的适配调整，可以个性化增加舞台灯光、地灯等","C. 打光到位可以不用控灯，灯光越亮越好"],
              answer: [0,1],
              explanation: "灯光不是越亮越好，需要合理控灯。AB正确。" },
            { id: 9, type: "multiple", question: "以下哪些行为不符合直播规范？（多选）",
              images: [],
              options: ["A. 直播过程中制造对立话题，引发矛盾冲突，叫嚣互怼","B. 主播穿着超短裙，大面积裸露腿部露出打底裤","C. 直播中通过反差形象博人眼球，营造拉踩竞争或卖惨","D. 团播团员超过1/2人穿着凸显身材性感服装"],
              answer: [0,1,2,3],
              explanation: "以上四项均违反直播规范。" },
            { id: 10, type: "multiple", question: "以下有利于呈现最佳上镜效果的是？（多选）",
              images: [],
              options: ["A. 避免过度美颜，导致面部轮廓随晃动变形","B. 避免滤镜过重造成面部惨白，色调偏青等不自然效果","C. 避免过度拉伸导致身体比例不协调造成的感官不适","D. 直播设置调成「蓝光」开播，有利于提高画面清晰度"],
              answer: [0,1,2,3],
              explanation: "以上四项都是达成最佳上镜效果的关键要点。" },
            { id: 11, type: "multiple", question: "团播直播中以下哪些行为违反主播行为规范？（多选）",
              images: [],
              options: ["A. 通过社交平台、群组、第三方APP渠道，以「打榜」「应援」「冲榜」等名义发起公开集资活动","B. 默许、刻意引导粉丝有组织性造谣抹黑，攻击谩骂他人","C. 通过私聊用户发送低俗暧昧、擦边撩人话术诱导打赏","D. 通过营造虚假人设、制造虚假亲密关系、虚假承诺、编造紧急求助等行为刺激打赏","E. 引导粉丝对团员数据、粉丝消费金额等做数据攀比，鼓吹炫耀"],
              answer: [0,1,2,3,4],
              explanation: "以上五项行为均严重违反平台主播行为规范。" },
            { id: 12, type: "multiple", question: "以下哪些服装或道具不可在直播过程中使用？（多选）",
              images: [],
              options: ["A. 红色、紫色调光灯形成的暧昧氛围","B. 蕾丝面具、皮鞭","C. 穿着露出勾线、凸点或看到内裤、隐私部位轮廓的着装","D. 镂空服饰、紧身连体衣、渔网袜渔网衣、破洞丝袜"],
              answer: [0,1,2,3],
              explanation: "以上四项均为直播中禁止使用的服装、道具和灯光效果。" },
            { id: 13, type: "single", question: "【高频问题】图中服装存在的问题是？（单选）",
              images: ["images/exam-hfyt/image3.png"],
              options: ["A. 穿JK等幼态服装","B. 下装过短，露出臀线/打底裤","C. 暴露的着装更容易带来曝光和观看"],
              answer: [1],
              explanation: "下装过短露出臀线或打底裤是高频违规问题。" },
            { id: 14, type: "single", question: "【高频问题】以下团播直播间场景涉及违规点是？（单选）",
              images: ["images/exam-hfyt/image4.png"],
              options: ["A. 台球室","B. KTV包厢","C. 办公室","D. 星空布"],
              answer: [2],
              explanation: "办公室场景属于娱乐化职场行业，是平台重点整治的违规场景。" },
            { id: 15, type: "single", question: "【高频问题】以下团播直播间场景涉及违规点是？（单选）",
              images: ["images/exam-hfyt/image5.png"],
              options: ["A. 教室场景","B. 包间围/转餐桌","C. 赌场场景","D. 娱乐化职场、教育行业"],
              answer: [1],
              explanation: "包间围/转餐桌属于餐饮包间类违规场景。" }
        ]
    },

    "exam-lwjz": {
        title: "抖音礼物价值基础",
        questions: [
            { id: 1, type: "single", question: "抖音充值10块钱是多少钻石？（单选）",
              images: [],
              options: ["A. 1钻","B. 10钻","C. 100钻","D. 1000钻"],
              answer: [2],
              explanation: "1钻=1毛钱，10钻=1块钱，100钻=10块钱，1000钻=100块钱，10000钻=1000块钱。" },
            { id: 2, type: "multiple", question: "下列哪些是属于价值99钻的礼物？（多选）",
              images: ["images/exam-lwjz/image1.png","images/exam-lwjz/image2.png","images/exam-lwjz/image3.png","images/exam-lwjz/image4.png","images/exam-lwjz/image5.png","images/exam-lwjz/image6.png","images/exam-lwjz/image7.png","images/exam-lwjz/image8.png","images/exam-lwjz/image9.png"],
              options: ["A. 闪耀星辰","B. 墨镜","C. 亲吻","D. 比心","E. 趣玩泡泡","F. 爱的纸鹤","G. 礼花筒","H. 荧光棒","I. 捏捏小脸"],
              answer: [0,1,2,4,5,7,8],
              explanation: "99钻礼物包括：闪耀星辰、墨镜、亲吻、趣玩泡泡、爱的纸鹤、荧光棒、捏捏小脸。比心（199钻）和礼花筒排除。" },
            { id: 3, type: "multiple", question: "下列哪些属于价值1钻的礼物？（多选）",
              images: ["images/exam-lwjz/image10.png","images/exam-lwjz/image11.png","images/exam-lwjz/image12.png","images/exam-lwjz/image13.png","images/exam-lwjz/image14.png","images/exam-lwjz/image15.png"],
              options: ["A. 小心心","B. 小抖音","C. 玫瑰","D. 你最好看","E. 人气票","F. 大啤酒"],
              answer: [0,1,2,4],
              explanation: "1钻礼物包括：小心心、小抖音、玫瑰、人气票。" },
            { id: 4, type: "multiple", question: "爱你呦和送你花花的价值分别是多少？（多选）",
              images: ["images/exam-lwjz/image16.png","images/exam-lwjz/image17.png"],
              options: ["A. 爱你哟 49钻","B. 送你花花 49钻","C. 送你花花 52钻","D. 爱你哟 52钻"],
              answer: [1,3],
              explanation: "送你花花价值49钻，爱你哟价值52钻。" },
            { id: 5, type: "multiple", question: "比心兔兔和比心的价值分别是多少？（多选）",
              images: ["images/exam-lwjz/image18.png","images/exam-lwjz/image4.png"],
              options: ["A. 比心兔兔 299钻","B. 比心 299钻","C. 比心兔兔 199钻","D. 比心 199钻"],
              answer: [0,3],
              explanation: "比心兔兔价值299钻，比心价值199钻。" },
            { id: 6, type: "multiple", question: "为你举牌和拳拳出击价值分别是多少？（多选）",
              images: ["images/exam-lwjz/image19.png","images/exam-lwjz/image20.png"],
              options: ["A. 为你举牌 299钻","B. 拳拳出击 199钻","C. 为你举牌 99钻","D. 拳拳出击 99钻","E. 为你举牌 199钻","F. 拳拳出击 299钻"],
              answer: [1,4],
              explanation: "为你举牌价值199钻，拳拳出击价值199钻。两个礼物价格相同。" },
            { id: 7, type: "truefalse", question: "以下礼物的价值都是520钻。",
              images: ["images/exam-lwjz/image21.png","images/exam-lwjz/image22.png"],
              options: ["正确","错误"],
              answer: [0],
              explanation: "所列礼物价值均为520钻。" },
            { id: 8, type: "truefalse", question: "以下礼物的价值都是599钻。",
              images: ["images/exam-lwjz/image23.png","images/exam-lwjz/image24.png"],
              options: ["正确","错误"],
              answer: [1],
              explanation: "图一是浪漫花火价值599钻，图二是万象烟花价值688钻。万象烟花不是599钻。" },
            { id: 9, type: "truefalse", question: "以下礼物价值都是366钻。",
              images: ["images/exam-lwjz/image25.png","images/exam-lwjz/image26.png"],
              options: ["正确","错误"],
              answer: [0],
              explanation: "图一是真爱玫瑰，图二是一束花开，价值均为366钻。" },
            { id: 10, type: "truefalse", question: "以下礼物价值都是599钻。",
              images: ["images/exam-lwjz/image27.png","images/exam-lwjz/image28.png"],
              options: ["正确","错误"],
              answer: [0],
              explanation: "图一是娶你回家，图二是爱情树下，价值均为599钻。" },
            { id: 11, type: "fill", question: "永生花礼物价值是多少？（格式：XX钻，如 520钻）",
              images: ["images/exam-lwjz/image29.png"],
              answer: "520钻",
              explanation: "永生花价值520钻。" },
            { id: 12, type: "fill", question: "跑车礼物价值是多少？（格式：XX钻，如 1200钻）",
              images: ["images/exam-lwjz/image30.png"],
              answer: "1200钻",
              explanation: "跑车价值1200钻。" },
            { id: 13, type: "fill", question: "浪漫营地礼物价值是多少？（格式：XX钻，如 1699钻）",
              images: ["images/exam-lwjz/image31.png"],
              answer: "1699钻",
              explanation: "浪漫营地价值1699钻。" },
            { id: 14, type: "fill", question: "花海泛舟礼物价值是多少？（格式：XX钻，如 2800钻）",
              images: ["images/exam-lwjz/image32.png"],
              answer: "2800钻",
              explanation: "花海泛舟价值2800钻。" },
            { id: 15, type: "fill", question: "私人飞机礼物价值是多少？（格式：XX钻，如 3000钻）",
              images: ["images/exam-lwjz/image33.png"],
              answer: "3000钻",
              explanation: "私人飞机价值3000钻。" },
            { id: 16, type: "fill", question: "浪漫恋人礼物价值是多少？（格式：XX钻，如 1999钻）",
              images: ["images/exam-lwjz/image34.png"],
              answer: "1999钻",
              explanation: "浪漫恋人价值1999钻。" },
            { id: 17, type: "single", question: "抖音一号和云中秘境哪个礼物更大（价值更高）？（单选）",
              images: ["images/exam-lwjz/image35.png","images/exam-lwjz/image36.png"],
              options: ["A. 抖音一号更大","B. 云中秘境更大","C. 一样大"],
              answer: [1],
              explanation: "抖音一号价值10001钻，云中秘境价值13140钻。云中秘境更大。" },
            { id: 18, type: "single", question: "以下礼物从小到大排序正确的是？（单选）",
              images: [],
              options: ["A. 豪华邮轮＜抖音飞艇＜抖音一号＜嘉年华","B. 抖音飞艇＜豪华邮轮＜抖音一号＜嘉年华","C. 豪华邮轮＜抖音一号＜抖音飞艇＜嘉年华","D. 抖音飞艇＜抖音一号＜豪华邮轮＜嘉年华"],
              answer: [2],
              explanation: "豪华邮轮6000钻＜抖音一号10001钻＜抖音飞艇20000钻＜嘉年华30000钻。" },
            { id: 19, type: "fill", question: "如果需要1568票/分/钻复活，此时需要多少个99的礼物算拉票成功？（格式：XX个，如 16个）",
              images: [],
              answer: "16个",
              explanation: "1568约等于1600，1600÷99≈16.16，用四舍五入法所以是16个，不是15个。" }
        ]
    }
};
