// ESLint 基础配置 — 配合 pre-commit hook 做代码质量检查
// 使用 flat config 格式（ESLint 10.x），无外部插件依赖
module.exports = [
  // 忽略 node_modules 和构建产物
  {
    ignores: ["node_modules/**", "dist/**", "build/**", ".claude/**"],
  },

  // 项目 JS 文件规则
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: {
        // === 浏览器标准 API ===
        window: "readonly",
        document: "readonly",
        console: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        URL: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        crypto: "readonly",
        btoa: "readonly",
        atob: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        Node: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLButtonElement: "readonly",
        EventTarget: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        // === 第三方库（通过 CDN / script 标签加载）===
        JSZip: "readonly",
        XLSX: "readonly",
        // === 项目内部全局（通过 script 标签加载的其他 JS 文件）===
        App: "readonly",
        DB: "readonly",
        Auth: "readonly",
        Trainer: "readonly",
        Trainee: "readonly",
        Cognition: "readonly",
        Importer: "readonly",
        Modal: "readonly",
        Defaults: "readonly",
        PASS_THRESHOLD: "readonly",
        DATA_VERSION: "readonly",
        GITHUB_CONFIG: "readonly",
        escapeHtml: "readonly",
        toggleAccordion: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-console": "off",
      "no-debugger": "warn",
      "no-empty": "warn",
      "no-extra-semi": "warn",
      "no-irregular-whitespace": "warn",
      "no-unreachable": "warn",
    },
  },
];
